const express = require('express')
const path = require('path')
const app = express()
const port = process.env.PORT || 5000

app.get('/', (request, response) => {
    response.send('<h1>HTML generated by the node server.</h1>')
})

app.listen(port, () => {
    console.log(`Server is listening on PORT: ${port}...`)
})
