const express = require('express')
const path = require('path')
const bodyParser = require('body-parser')
const cors = require('cors')
const morgan = require('morgan')

const app = express()
app.use(morgan('combine'))
app.use(bodyParser.json())
app.use(cors())

const port = process.env.PORT || 5000

app.listen(port, () => {
    console.log(`Server is listening on PORT: ${port}...`)
})

app.get('/', (request, response) => {
    response.send('<h1>HTML generated by the node server.</h1>')
})

const scrapper = setInterval(() => {
    console.log('log from server..')
}, 10000);